import { PreferenceOption } from "@/types/preferences";

export const toolCategories = [
  {
    id: "general",
    title: "General - For All",
    description: "Universal tools designed to enhance productivity and streamline workflows for everyone.",
    tools: [
      {
        id: "general-tool-box",
        title: "General Tool Box",
        subtitle: "For All",
        description: "A collection of versatile tools for various tasks.",
        logo: "/logo,png",
        screenshot: ["/images/general-toolbox.png"],
        coins: "Free",
        href: "/general-tool-box",
        tags: ["productivity", "utility"],
        isNew: true,
      },
      {
        id: "shashank",
        title: "Shashank - AI",
        subtitle: "Very best tool in the world",
        description: "Shashank is used to create a good image and talk with image.",
        logo: "/logo.png",
        screenshot: ["/logo.png", "/ss.png"],
        coins: "Free",
        href: "/shashank",
        tags: ["productivity", "designer", "marketing"],
        isNew: false,
      },
      {
        id: "kavya",
        title: "Kavya",
        subtitle: "For All",
        description: "A psychiatric advisor for mental health support.",
        logo: "/logo,png",
        screenshot: ["/images/kavya.png"],
        coins: "Free",
        href: "/kavya",
        tags: ["healthcare", "support"],
        isNew: true,
      },
      {
        id: "maya-career",
        title: "Maya - Career Counsellor",
        subtitle: "For All",
        description: "A career counselling tool to help you find your path.",
        logo: "/logo,png",
        screenshot: ["/images/maya.png"],
        coins: "Free",
        href: "/maya-career",
        tags: ["education", "career"],
        isNew: true,
      },
      {
        id: "image-generator",
        title: "Image Generator",
        subtitle: "For All",
        description: "Generate images based on your input.",
        logo: "/logo,png",
        screenshot: ["/images/image-generator.png"],
        coins: "Free",
        href: "/image-generator",
        tags: ["designer", "creativity"],
        isNew: true,
      },
      {
        id: "ai-ocr-translation",
        title: "AI OCR & Translation",
        subtitle: "For All",
        description: "Optical Character Recognition and translation tool.",
        logo: "/logo,png",
        screenshot: ["/images/ocr-translation.png"],
        coins: "Free",
        href: "/ai-ocr-translation",
        tags: ["writing", "translation"],
        isNew: true,
      },
      {
        id: "ai-video-generator",
        title: "AI Video Generator",
        subtitle: "For All",
        description: "Generate videos based on your input.",
        logo: "/logo,png",
        screenshot: ["/images/video-generator.png"],
        coins: "Free",
        href: "/ai-video-generator",
        tags: ["designer", "marketing"],
        isNew: true,
      },
      {
        id: "ai-audio-enhancer",
        title: "AI Audio Enhancer",
        subtitle: "For All",
        description: "Enhance your audio files with AI.",
        logo: "/logo,png",
        screenshot: ["/images/audio-enhancer.png"],
        coins: "Free",
        href: "/ai-audio-enhancer",
        tags: ["designer", "audio"],
        isNew: true,
      },
      {
        id: "ai-text-to-speech",
        title: "AI Text to Speech",
        subtitle: "For All",
        description: "Convert text to natural-sounding speech.",
        logo: "/logo,png",
        screenshot: ["/images/text-to-speech.png"],
        coins: "Free",
        href: "/ai-text-to-speech",
        tags: ["writing", "audio"],
        isNew: true,
      },
      {
        id: "logo-generation",
        title: "Logo Generation",
        subtitle: "For All",
        description: "Create unique logos with AI.",
        logo: "/logo,png",
        screenshot: ["/images/logo-generation.png"],
        coins: "Free",
        href: "/logo-generation",
        tags: ["designer", "branding"],
        isNew: true,
      },
      {
        id: "stock-image",
        title: "Stock Image",
        subtitle: "For All",
        description: "Access a library of stock images.",
        logo: "/logo,png",
        screenshot: ["/images/stock-image.png"],
        coins: "Free",
        href: "/stock-image",
        tags: ["designer", "resources"],
        isNew: true,
      },
      {
        id: "chat-with-image",
        title: "Chat With Image",
        subtitle: "For All",
        description: "Engage in conversations with images.",
        logo: "/logo,png",
        screenshot: ["/images/chat-with-image.png"],
        coins: "Free",
        href: "/chat-with-image",
        tags: ["social", "designer"],
        isNew: true,
      },
      {
        id: "transcribe-audio",
        title: "Transcribe Audio",
        subtitle: "For All",
        description: "Convert audio recordings to text.",
        logo: "/logo,png",
        screenshot: ["/images/transcribe-audio.png"],
        coins: "Free",
        href: "/transcribe-audio",
        tags: ["writing", "audio"],
        isNew: true,
      },
      {
        id: "music-tune-gen",
        title: "Music Tune Gen",
        subtitle: "For All",
        description: "Generate unique music tunes.",
        logo: "/logo,png",
        screenshot: ["/images/music-tune-gen.png"],
        coins: "Free",
        href: "/music-tune-gen",
        tags: ["designer", "music"],
        isNew: true,
      },
      {
        id: "voice-clone-ai",
        title: "Voice Clone AI",
        subtitle: "For All",
        description: "Clone voices with AI technology.",
        logo: "/logo,png",
        screenshot: ["/images/voice-clone-ai.png"],
        coins: "Free",
        href: "/voice-clone-ai",
        tags: ["designer", "audio"],
        isNew: true,
      },
      {
        id: "vocal-shift-ai",
        title: "Vocal Shift AI",
        subtitle: "For All",
        description: "Shift vocal characteristics in audio.",
        logo: "/logo,png",
        screenshot: ["/images/vocal-shift-ai.png"],
        coins: "Free",
        href: "/vocal-shift-ai",
        tags: ["designer", "audio"],
        isNew: true,
      },
    ],
  },
];

export const PREFERENCE_OPTIONS: PreferenceOption[] = [
  {
    id: "productivity",
    title: "Productivity & Organization",
    description: "Tools to boost your efficiency and organize your work",
    tags: ["productivity", "utility", "organization"],
    icon: "⚡"
  },
  {
    id: "design_creative",
    title: "Design & Creative",
    description: "Create stunning visuals, logos, and multimedia content",
    tags: ["designer", "creativity", "branding", "audio", "music"],
    icon: "🎨"
  },
  {
    id: "marketing_business",
    title: "Marketing & Business",
    description: "Grow your business and enhance your marketing efforts",
    tags: ["marketing", "business", "social", "branding"],
    icon: "📈"
  },
  {
    id: "writing_content",
    title: "Writing & Content",
    description: "Create, edit, and translate written content",
    tags: ["writing", "content", "translation"],
    icon: "✍️"
  },
  {
    id: "health_wellness",
    title: "Health & Wellness",
    description: "Mental health support and wellness tools",
    tags: ["healthcare", "support", "wellness"],
    icon: "🏥"
  },
  {
    id: "education_career",
    title: "Education & Career",
    description: "Learn new skills and advance your career",
    tags: ["education", "career", "learning"],
    icon: "🎓"
  },
  {
    id: "finance_fintech",
    title: "Finance & FinTech",
    description: "Manage finances and explore financial technologies",
    tags: ["finance", "fintech", "investment", "budgeting"],
    icon: "💰"
  },
  {
    id: "development_tech",
    title: "Development & Tech",
    description: "Programming tools and technical resources",
    tags: ["development", "programming", "tech", "coding"],
    icon: "💻"
  },
  {
    id: "data_analytics",
    title: "Data & Analytics",
    description: "Analyze data and generate insights",
    tags: ["analytics", "data", "insights", "reporting"],
    icon: "📊"
  },
  {
    id: "communication",
    title: "Communication & Collaboration",
    description: "Connect and collaborate with others effectively",
    tags: ["communication", "collaboration", "teamwork"],
    icon: "💬"
  }
];