import { PreferenceOption } from "@/types/preferences";

export const toolCategories = [
  {
    id: "general",
    title: "General - For All",
    description: "Universal tools designed to enhance productivity and streamline workflows for everyone.",
    tools: [
      {
        id: "general-tool-box",
        title: "General Tool Box",
        subtitle: "For All",
        description: "A collection of versatile tools for various tasks.",
        logo: "https://default-logo.com/placeholder.png",
        screenshot: ["/images/general-toolbox.png"],
        coins: "Free",
        href: "/general-tool-box",
        tags: ["productivity", "utility"],
        isNew: true,
      },
      {
        id: "shashank",
        title: "Shashank - AI",
        subtitle: "Very best tool in the world",
        description: "Shashank is used to create a good image and talk with image.",
        logo: "/logo.png",
        screenshot: ["/logo.png", "/ss.png"],
        coins: "Free",
        href: "/shashank",
        tags: ["productivity", "designer", "marketing"],
        isNew: false,
      },
      {
        id: "kavya",
        title: "Kavya",
        subtitle: "For All",
        description: "A psychiatric advisor for mental health support.",
        logo: "https://default-logo.com/placeholder.png",
        screenshot: ["/images/kavya.png"],
        coins: "Free",
        href: "/kavya",
        tags: ["healthcare", "support"],
        isNew: true,
      },
      {
        id: "maya-career",
        title: "Maya - Career Counsellor",
        subtitle: "For All",
        description: "A career counselling tool to help you find your path.",
        logo: "https://default-logo.com/placeholder.png",
        screenshot: ["/images/maya.png"],
        coins: "Free",
        href: "/maya-career",
        tags: ["education", "career"],
        isNew: true,
      },
      {
        id: "image-generator",
        title: "Image Generator",
        subtitle: "For All",
        description: "Generate images based on your input.",
        logo: "https://default-logo.com/placeholder.png",
        screenshot: ["/images/image-generator.png"],
        coins: "Free",
        href: "/image-generator",
        tags: ["designer", "creativity"],
        isNew: true,
      },
      {
        id: "ai-ocr-translation",
        title: "AI OCR & Translation",
        subtitle: "For All",
        description: "Optical Character Recognition and translation tool.",
        logo: "https://default-logo.com/placeholder.png",
        screenshot: ["/images/ocr-translation.png"],
        coins: "Free",
        href: "/ai-ocr-translation",
        tags: ["writing", "translation"],
        isNew: true,
      },
      {
        id: "ai-video-generator",
        title: "AI Video Generator",
        subtitle: "For All",
        description: "Generate videos based on your input.",
        logo: "https://default-logo.com/placeholder.png",
        screenshot: ["/images/video-generator.png"],
        coins: "Free",
        href: "/ai-video-generator",
        tags: ["designer", "marketing"],
        isNew: true,
      },
      {
        id: "ai-audio-enhancer",
        title: "AI Audio Enhancer",
        subtitle: "For All",
        description: "Enhance your audio files with AI.",
        logo: "https://default-logo.com/placeholder.png",
        screenshot: ["/images/audio-enhancer.png"],
        coins: "Free",
        href: "/ai-audio-enhancer",
        tags: ["designer", "audio"],
        isNew: true,
      },
      {
        id: "ai-text-to-speech",
        title: "AI Text to Speech",
        subtitle: "For All",
        description: "Convert text to natural-sounding speech.",
        logo: "https://default-logo.com/placeholder.png",
        screenshot: ["/images/text-to-speech.png"],
        coins: "Free",
        href: "/ai-text-to-speech",
        tags: ["writing", "audio"],
        isNew: true,
      },
      {
        id: "logo-generation",
        title: "Logo Generation",
        subtitle: "For All",
        description: "Create unique logos with AI.",
        logo: "https://default-logo.com/placeholder.png",
        screenshot: ["/images/logo-generation.png"],
        coins: "Free",
        href: "/logo-generation",
        tags: ["designer", "branding"],
        isNew: true,
      },
      {
        id: "stock-image",
        title: "Stock Image",
        subtitle: "For All",
        description: "Access a library of stock images.",
        logo: "https://default-logo.com/placeholder.png",
        screenshot: ["/images/stock-image.png"],
        coins: "Free",
        href: "/stock-image",
        tags: ["designer", "resources"],
        isNew: true,
      },
      {
        id: "chat-with-image",
        title: "Chat With Image",
        subtitle: "For All",
        description: "Engage in conversations with images.",
        logo: "https://default-logo.com/placeholder.png",
        screenshot: ["/images/chat-with-image.png"],
        coins: "Free",
        href: "/chat-with-image",
        tags: ["social", "designer"],
        isNew: true,
      },
      {
        id: "transcribe-audio",
        title: "Transcribe Audio",
        subtitle: "For All",
        description: "Convert audio recordings to text.",
        logo: "https://default-logo.com/placeholder.png",
        screenshot: ["/images/transcribe-audio.png"],
        coins: "Free",
        href: "/transcribe-audio",
        tags: ["writing", "audio"],
        isNew: true,
      },
      {
        id: "music-tune-gen",
        title: "Music Tune Gen",
        subtitle: "For All",
        description: "Generate unique music tunes.",
        logo: "https://default-logo.com/placeholder.png",
        screenshot: ["/images/music-tune-gen.png"],
        coins: "Free",
        href: "/music-tune-gen",
        tags: ["designer", "music"],
        isNew: true,
      },
      {
        id: "voice-clone-ai",
        title: "Voice Clone AI",
        subtitle: "For All",
        description: "Clone voices with AI technology.",
        logo: "https://default-logo.com/placeholder.png",
        screenshot: ["/images/voice-clone-ai.png"],
        coins: "Free",
        href: "/voice-clone-ai",
        tags: ["designer", "audio"],
        isNew: true,
      },
      {
        id: "vocal-shift-ai",
        title: "Vocal Shift AI",
        subtitle: "For All",
        description: "Shift vocal characteristics in audio.",
        logo: "https://default-logo.com/placeholder.png",
        screenshot: ["/images/vocal-shift-ai.png"],
        coins: "Free",
        href: "/vocal-shift-ai",
        tags: ["designer", "audio"],
        isNew: true,
      },
    ],
  },
  {
    id: "education",
    title: "Education Tools",
    description: "Learning resources and study aids to help students and educators achieve better results.",
    tools: [
      {
        id: "education-tool-box",
        title: "Education Tool Box",
        subtitle: "For All",
        description: "A collection of educational tools for students and teachers.",
        logo: "https://default-logo.com/placeholder.png",
        screenshot: ["/images/education-toolbox.png"],
        coins: "Free",
        href: "/education-tool-box",
        tags: ["education", "learning"],
        isNew: true,
      },
      {
        id: "maya-career-counsellor",
        title: "Maya - Career Counsellor",
        subtitle: "For All",
        description: "A career counselling tool to help you find your path.",
        logo: "https://default-logo.com/placeholder.png",
        screenshot: ["/images/maya.png"],
        coins: "Free",
        href: "/maya-career-counsellor",
        tags: ["education", "career"],
        isNew: true,
      },
      {
        id: "ananya-coding",
        title: "Ananya - Coding Assistant",
        subtitle: "For All",
        description: "A coding assistant to help with programming tasks.",
        logo: "https://default-logo.com/placeholder.png",
        screenshot: ["/images/coding-assistant.png"],
        coins: "Free",
        href: "/ananya-coding",
        tags: ["education", "coding"],
        isNew: true,
      },
      {
        id: "shashank-assistant",
        title: "Shashank - Helpful Assistant",
        subtitle: "For All",
        description: "A helpful assistant for various tasks.",
        logo: "https://default-logo.com/placeholder.png",
        screenshot: ["/images/shashank.png"],
        coins: "Free",
        href: "/shashank-assistant",
        tags: ["education", "productivity"],
        isNew: true,
      },
      {
        id: "image-generation-edu",
        title: "Image Generation",
        subtitle: "For All",
        description: "Generate images based on your input.",
        logo: "https://default-logo.com/placeholder.png",
        screenshot: ["/images/image-generation.png"],
        coins: "Free",
        href: "/image-generation-edu",
        tags: ["education", "designer"],
        isNew: true,
      },
      {
        id: "diagram-flow",
        title: "Diagram Flow",
        subtitle: "For All",
        description: "Create flow diagrams easily.",
        logo: "https://default-logo.com/placeholder.png",
        screenshot: ["/images/diagram-flow.png"],
        coins: "Free",
        href: "/diagram-flow",
        tags: ["education", "diagrams"],
        isNew: true,
      },
      {
        id: "studybuddy",
        title: "StudyBuddy",
        subtitle: "For All",
        description: "A study companion to help with learning.",
        logo: "https://default-logo.com/placeholder.png",
        screenshot: ["/images/studybuddy.png"],
        coins: "Free",
        href: "/studybuddy",
        tags: ["education", "learning"],
        isNew: true,
      },
      {
        id: "lingolearn",
        title: "LingoLearn",
        subtitle: "For All",
        description: "A language learning tool.",
        logo: "https://default-logo.com/placeholder.png",
        screenshot: ["/images/lingolearn.png"],
        coins: "Free",
        href: "/lingolearn",
        tags: ["education", "language"],
        isNew: true,
      },
      {
        id: "ai-digitalboard",
        title: "AI DigitalBoard",
        subtitle: "For All",
        description: "An interactive digital board for presentations.",
        logo: "https://default-logo.com/placeholder.png",
        screenshot: ["/images/digitalboard.png"],
        coins: "Free",
        href: "/ai-digitalboard",
        tags: ["education", "presentation"],
        isNew: true,
      },
      {
        id: "chat-with-image-edu",
        title: "Chat With Image",
        subtitle: "For All",
        description: "Engage in conversations with images.",
        logo: "https://default-logo.com/placeholder.png",
        screenshot: ["/images/chat-with-image.png"],
        coins: "Free",
        href: "/chat-with-image-edu",
        tags: ["education", "social"],
        isNew: true,
      },
      {
        id: "image-extract-ai",
        title: "Image Extract AI",
        subtitle: "For All",
        description: "Extract information from images.",
        logo: "https://default-logo.com/placeholder.png",
        screenshot: ["/images/image-extract-ai.png"],
        coins: "Free",
        href: "/image-extract-ai",
        tags: ["education", "designer"],
        isNew: true,
      },
      {
        id: "readme-git-genie",
        title: "ReadmeGitGenie",
        subtitle: "For All",
        description: "A tool to generate README files from your code.",
        logo: "https://default-logo.com/placeholder.png",
        screenshot: ["/images/readme-genie.png"],
        coins: "Free",
        href: "/readme-git-genie",
        tags: ["education", "coding"],
        isNew: true,
      },
    ],
  },
  {
    id: "writing",
    title: "Writing Tools",
    description: "Creative and professional writing assistants to help craft compelling content.",
    tools: [
      {
        id: "writegenius",
        title: "WriteGenius",
        subtitle: "For All",
        description: "A writing assistant to help with various writing tasks.",
        logo: "https://default-logo.com/placeholder.png",
        screenshot: ["/images/writegenius.png"],
        coins: "Free",
        href: "/writegenius",
        tags: ["writing", "productivity"],
        isNew: true,
      },
      {
        id: "assignmentcreator",
        title: "AssignmentCreator",
        subtitle: "For All",
        description: "Create assignments easily.",
        logo: "https://default-logo.com/placeholder.png",
        screenshot: ["/images/assignmentcreator.png"],
        coins: "Free",
        href: "/assignmentcreator",
        tags: ["writing", "education"],
        isNew: true,
      },
      {
        id: "grammatical",
        title: "Grammatical",
        subtitle: "For All",
        description: "A grammar checking tool.",
        logo: "https://default-logo.com/placeholder.png",
        screenshot: ["/images/grammatical.png"],
        coins: "Free",
        href: "/grammatical",
        tags: ["writing", "grammar"],
        isNew: true,
      },
      {
        id: "question-paper-generator",
        title: "Question Paper Generator",
        subtitle: "For All",
        description: "Generate question papers for exams.",
        logo: "https://default-logo.com/placeholder.png",
        screenshot: ["/images/question-paper-generator.png"],
        coins: "Free",
        href: "/question-paper-generator",
        tags: ["writing", "education"],
        isNew: true,
      },
      {
        id: "language-translator",
        title: "Language Translator",
        subtitle: "For All",
        description: "Translate text between different languages.",
        logo: "https://default-logo.com/placeholder.png",
        screenshot: ["/images/language-translator.png"],
        coins: "Free",
        href: "/language-translator",
        tags: ["writing", "translation"],
        isNew: true,
      },
      {
        id: "text-simplifier",
        title: "TextSimplifier",
        subtitle: "For All",
        description: "Simplify complex text for better understanding.",
        logo: "https://default-logo.com/placeholder.png",
        screenshot: ["/images/text-simplifier.png"],
        coins: "Free",
        href: "/text-simplifier",
        tags: ["writing", "editing"],
        isNew: true,
      },
      {
        id: "report-maker",
        title: "Report Maker",
        subtitle: "For All",
        description: "Create reports easily.",
        logo: "https://default-logo.com/placeholder.png",
        screenshot: ["/images/report-maker.png"],
        coins: "Free",
        href: "/report-maker",
        tags: ["writing", "productivity"],
        isNew: true,
      },
      {
        id: "plagiarism-checker",
        title: "Plagiarism Checker",
        subtitle: "For All",
        description: "Check for plagiarism in your text.",
        logo: "https://default-logo.com/placeholder.png",
        screenshot: ["/images/plagiarism-checker.png"],
        coins: "Free",
        href: "/plagiarism-checker",
        tags: ["writing", "verification"],
        isNew: true,
      },
      {
        id: "message-generator",
        title: "MessageGenerator",
        subtitle: "For All",
        description: "Generate messages for various purposes.",
        logo: "https://default-logo.com/placeholder.png",
        screenshot: ["/images/message-generator.png"],
        coins: "Free",
        href: "/message-generator",
        tags: ["writing", "communication"],
        isNew: true,
      },
      {
        id: "blog-title",
        title: "Blog Title",
        subtitle: "For All",
        description: "Generate titles for blog posts.",
        logo: "https://default-logo.com/placeholder.png",
        screenshot: ["/images/blog-title.png"],
        coins: "Free",
        href: "/blog-title",
        tags: ["writing", "marketing"],
        isNew: true,
      },
      {
        id: "essay-writer",
        title: "Essay Writer",
        subtitle: "For All",
        description: "A tool to help write essays.",
        logo: "https://default-logo.com/placeholder.png",
        screenshot: ["/images/essay-writer.png"],
        coins: "Free",
        href: "/essay-writer",
        tags: ["writing", "education"],
        isNew: true,
      },
      {
        id: "chapter-generator",
        title: "Chapter Generator",
        subtitle: "For All",
        description: "Generate chapters for books or stories.",
        logo: "https://default-logo.com/placeholder.png",
        screenshot: ["/images/chapter-generator.png"],
        coins: "Free",
        href: "/chapter-generator",
        tags: ["writing", "creativity"],
        isNew: true,
      },
      {
        id: "speech-generator",
        title: "Speech Generator",
        subtitle: "For All",
        description: "Create speeches for various occasions.",
        logo: "https://default-logo.com/placeholder.png",
        screenshot: ["/images/speech-generator.png"],
        coins: "Free",
        href: "/speech-generator",
        tags: ["writing", "communication"],
        isNew: true,
      },
      {
        id: "newsletter-content-generator",
        title: "Newsletter Content Generator",
        subtitle: "For All",
        description: "Generate content for newsletters.",
        logo: "https://default-logo.com/placeholder.png",
        screenshot: ["/images/newsletter-content-generator.png"],
        coins: "Free",
        href: "/newsletter-content-generator",
        tags: ["writing", "marketing"],
        isNew: true,
      },
      {
        id: "blog-post-idea-generator",
        title: "Blog Post Idea Generator",
        subtitle: "For All",
        description: "Generate ideas for blog posts.",
        logo: "https://default-logo.com/placeholder.png",
        screenshot: ["/images/blog-post-idea-generator.png"],
        coins: "Free",
        href: "/blog-post-idea-generator",
        tags: ["writing", "marketing"],
        isNew: true,
      },
      {
        id: "quora-answer-generator",
        title: "Quora Answer Generator",
        subtitle: "For All",
        description: "Generate answers for Quora questions.",
        logo: "https://default-logo.com/placeholder.png",
        screenshot: ["/images/quora-answer-generator.png"],
        coins: "Free",
        href: "/quora-answer-generator",
        tags: ["writing", "social"],
        isNew: true,
      },
      {
        id: "reddit-post-idea-generator",
        title: "Reddit Post Idea Generator",
        subtitle: "For All",
        description: "Generate ideas for Reddit posts.",
        logo: "https://default-logo.com/placeholder.png",
        screenshot: ["/images/reddit-post-idea-generator.png"],
        coins: "Free",
        href: "/reddit-post-idea-generator",
        tags: ["writing", "social"],
        isNew: true,
      },
      {
        id: "application-writing-generator",
        title: "Application Writing Generator",
        subtitle: "For All",
        description: "Generate applications for various purposes.",
        logo: "https://default-logo.com/placeholder.png",
        screenshot: ["/images/application-writing-generator.png"],
        coins: "Free",
        href: "/application-writing-generator",
        tags: ["writing", "professional"],
        isNew: true,
      },
      {
        id: "resume-bullet-point-generator",
        title: "Resume Bullet Point Generator",
        subtitle: "For All",
        description: "Generate bullet points for resumes.",
        logo: "https://default-logo.com/placeholder.png",
        screenshot: ["/images/resume-bullet-point-generator.png"],
        coins: "Free",
        href: "/resume-bullet-point-generator",
        tags: ["writing", "career"],
        isNew: true,
      },
      {
        id: "cover-letter-generator",
        title: "Cover Letter Generator",
        subtitle: "For All",
        description: "Generate cover letters for job applications.",
        logo: "https://default-logo.com/placeholder.png",
        screenshot: ["/images/cover-letter-generator.png"],
        coins: "Free",
        href: "/cover-letter-generator",
        tags: ["writing", "career"],
        isNew: true,
      },
      {
        id: "story-plot-generator",
        title: "Story Plot Generator",
        subtitle: "For All",
        description: "Generate plots for stories.",
        logo: "https://default-logo.com/placeholder.png",
        screenshot: ["/images/story-plot-generator.png"],
        coins: "Free",
        href: "/story-plot-generator",
        tags: ["writing", "creativity"],
        isNew: true,
      },
      {
        id: "character-name-generator",
        title: "Character Name Generator",
        subtitle: "For All",
        description: "Generate names for characters.",
        logo: "https://default-logo.com/placeholder.png",
        screenshot: ["/images/character-name-generator.png"],
        coins: "Free",
        href: "/character-name-generator",
        tags: ["writing", "creativity"],
        isNew: true,
      },
      {
        id: "blog-conclusion-generator",
        title: "Blog Conclusion Generator",
        subtitle: "For All",
        description: "Generate conclusions for blog posts.",
        logo: "https://default-logo.com/placeholder.png",
        screenshot: ["/images/blog-conclusion-generator.png"],
        coins: "Free",
        href: "/blog-conclusion-generator",
        tags: ["writing", "marketing"],
        isNew: true,
      },
      {
        id: "whitepaper-outline-generator",
        title: "Whitepaper Outline Generator",
        subtitle: "For All",
        description: "Generate outlines for whitepapers.",
        logo: "https://default-logo.com/placeholder.png",
        screenshot: ["/images/whitepaper-outline-generator.png"],
        coins: "Free",
        href: "/whitepaper-outline-generator",
        tags: ["writing", "professional"],
        isNew: true,
      },
      {
        id: "case-study-generator",
        title: "Case Study Generator",
        subtitle: "For All",
        description: "Generate case studies.",
        logo: "https://default-logo.com/placeholder.png",
        screenshot: ["/images/case-study-generator.png"],
        coins: "Free",
        href: "/case-study-generator",
        tags: ["writing", "marketing"],
        isNew: true,
      },
      {
        id: "film-script-generator",
        title: "Film Script Generator",
        subtitle: "For All",
        description: "Generate scripts for films.",
        logo: "https://default-logo.com/placeholder.png",
        screenshot: ["/images/film-script-generator.png"],
        coins: "Free",
        href: "/film-script-generator",
        tags: ["writing", "designer"],
        isNew: true,
      },
      {
        id: "cold-email-generator",
        title: "Cold Email Generator",
        subtitle: "For All",
        description: "Generate cold emails.",
        logo: "https://default-logo.com/placeholder.png",
        screenshot: ["/images/cold-email-generator.png"],
        coins: "Free",
        href: "/cold-email-generator",
        tags: ["writing", "marketing"],
        isNew: true,
      },
      {
        id: "webinar-content-generator",
        title: "Webinar Content Generator",
        subtitle: "For All",
        description: "Generate content for webinars.",
        logo: "https://default-logo.com/placeholder.png",
        screenshot: ["/images/webinar-content-generator.png"],
        coins: "Free",
        href: "/webinar-content-generator",
        tags: ["writing", "marketing"],
        isNew: true,
      },
      {
        id: "ebook-outline-generator",
        title: "Ebook Outline Generator",
        subtitle: "For All",
        description: "Generate outlines for ebooks.",
        logo: "https://default-logo.com/placeholder.png",
        screenshot: ["/images/ebook-outline-generator.png"],
        coins: "Free",
        href: "/ebook-outline-generator",
        tags: ["writing", "education"],
        isNew: true,
      },
      {
        id: "tiktok-script-generator",
        title: "TikTok Script Generator",
        subtitle: "For All",
        description: "Generate scripts for TikTok videos.",
        logo: "https://default-logo.com/placeholder.png",
        screenshot: ["/images/tiktok-script-generator.png"],
        coins: "Free",
        href: "/tiktok-script-generator",
        tags: ["writing", "social"],
        isNew: true,
      },
      {
        id: "instagram-bio-generator",
        title: "Instagram Bio Generator",
        subtitle: "For All",
        description: "Generate bios for Instagram profiles.",
        logo: "https://default-logo.com/placeholder.png",
        screenshot: ["/images/instagram-bio-generator.png"],
        coins: "Free",
        href: "/instagram-bio-generator",
        tags: ["writing", "social"],
        isNew: true,
      },
      {
        id: "linkedin-article-idea-generator",
        title: "LinkedIn Article Idea Generator",
        subtitle: "For All",
        description: "Generate ideas for LinkedIn articles.",
        logo: "https://default-logo.com/placeholder.png",
        screenshot: ["/images/linkedin-article-idea-generator.png"],
        coins: "Free",
        href: "/linkedin-article-idea-generator",
        tags: ["writing", "social"],
        isNew: true,
      },
      {
        id: "facebook-group-post-idea-generator",
        title: "Facebook Group Post Idea Generator",
        subtitle: "For All",
        description: "Generate ideas for Facebook group posts.",
        logo: "https://default-logo.com/placeholder.png",
        screenshot: ["/images/facebook-group-post-idea-generator.png"],
        coins: "Free",
        href: "/facebook-group-post-idea-generator",
        tags: ["writing", "social"],
        isNew: true,
      },
      {
        id: "ebook-title-generator",
        title: "Ebook Title Generator",
        subtitle: "For All",
        description: "Generate titles for ebooks.",
        logo: "https://default-logo.com/placeholder.png",
        screenshot: ["/images/ebook-title-generator.png"],
        coins: "Free",
        href: "/ebook-title-generator",
        tags: ["writing", "marketing"],
        isNew: true,
      },
      {
        id: "book-title-generator",
        title: "Book Title Generator",
        subtitle: "For All",
        description: "Generate titles for books.",
        logo: "https://default-logo.com/placeholder.png",
        screenshot: ["/images/book-title-generator.png"],
        coins: "Free",
        href: "/book-title-generator",
        tags: ["writing", "creativity"],
        isNew: true,
      },
      {
        id: "email-subject-line-generator",
        title: "Email Subject Line Generator",
        subtitle: "For All",
        description: "Generate subject lines for emails.",
        logo: "https://default-logo.com/placeholder.png",
        screenshot: ["/images/email-subject-line-generator.png"],
        coins: "Free",
        href: "/email-subject-line-generator",
        tags: ["writing", "marketing"],
        isNew: true,
      },
      {
        id: "email-generator",
        title: "Email Generator",
        subtitle: "For All",
        description: "Generate emails.",
        logo: "https://default-logo.com/placeholder.png",
        screenshot: ["/images/email-generator.png"],
        coins: "Free",
        href: "/email-generator",
        tags: ["writing", "marketing"],
        isNew: true,
      },
      {
        id: "ad-copy-generator",
        title: "Ad Copy Generator",
        subtitle: "For All",
        description: "Generate ad copy.",
        logo: "https://default-logo.com/placeholder.png",
        screenshot: ["/images/ad-copy-generator.png"],
        coins: "Free",
        href: "/ad-copy-generator",
        tags: ["writing", "marketing"],
        isNew: true,
      },
    ],
  },
  {
    id: "designer",
    title: "Designer Tools",
    description: "Creative resources for graphic designers, UI/UX professionals, and visual artists.",
    tools: [
      {
        id: "image-generation",
        title: "Image Generation",
        subtitle: "For All",
        description: "Generate images from text prompts.",
        logo: "https://default-logo.com/placeholder.png",
        screenshot: ["/images/image-generation.png"],
        coins: "Free",
        href: "/image-generation",
        tags: ["designer", "creativity"],
        isNew: true,
      },
      {
        id: "logo-generation",
        title: "Logo Generation",
        subtitle: "For All",
        description: "Create unique logos.",
        logo: "https://default-logo.com/placeholder.png",
        screenshot: ["/images/logo-generation.png"],
        coins: "Free",
        href: "/logo-generation",
        tags: ["designer", "branding"],
        isNew: true,
      },
      {
        id: "anime-image-generation",
        title: "Anime Image Generation",
        subtitle: "For All",
        description: "Generate anime-style images.",
        logo: "https://default-logo.com/placeholder.png",
        screenshot: ["/images/anime-image-generation.png"],
        coins: "Free",
        href: "/anime-image-generation",
        tags: ["designer", "creativity"],
        isNew: true,
      },
      {
        id: "stock-image",
        title: "Stock Image",
        subtitle: "For All",
        description: "Access a library of stock images.",
        logo: "https://default-logo.com/placeholder.png",
        screenshot: ["/images/stock-image.png"],
        coins: "Free",
        href: "/stock-image",
        tags: ["designer", "resources"],
        isNew: true,
      },
      {
        id: "interior-genius",
        title: "Interior Genius",
        subtitle: "For All",
        description: "Generate interior design ideas.",
        logo: "https://default-logo.com/placeholder.png",
        screenshot: ["/images/interior-genius.png"],
        coins: "Free",
        href: "/interior-genius",
        tags: ["designer", "interior"],
        isNew: true,
      },
      {
        id: "media-fixer-ai",
        title: "Media Fixer AI",
        subtitle: "For All",
        description: "Enhance and fix media content.",
        logo: "https://default-logo.com/placeholder.png",
        screenshot: ["/images/media-fixer-ai.png"],
        coins: "Free",
        href: "/media-fixer-ai",
        tags: ["designer", "editing"],
        isNew: true,
      },
      {
        id: "t-shirt-designer-ai",
        title: "T-Shirt Designer AI",
        subtitle: "For All",
        description: "Create custom t-shirt designs.",
        logo: "https://default-logo.com/placeholder.png",
        screenshot: ["/images/t-shirt-designer-ai.png"],
        coins: "Free",
        href: "/t-shirt-designer-ai",
        tags: ["designer", "creativity"],
        isNew: true,
      },
    ],
  },
  {
    id: "marketing",
    title: "Marketing Tools",
    description: "Promotional and analytical tools to boost your brand presence and engagement.",
    tools: [
      {
        id: "revenue-predictor",
        title: "RevenuePredictor",
        subtitle: "For All",
        description: "Predict revenue based on various factors.",
        logo: "https://default-logo.com/placeholder.png",
        screenshot: ["/images/revenue-predictor.png"],
        coins: "Free",
        href: "/revenue-predictor",
        tags: ["marketing", "analytics"],
        isNew: true,
      },
      {
        id: "product-info",
        title: "ProductInfo",
        subtitle: "For All",
        description: "Get detailed information about products.",
        logo: "https://default-logo.com/placeholder.png",
        screenshot: ["/images/product-info.png"],
        coins: "Free",
        href: "/product-info",
        tags: ["marketing", "ecommerce"],
        isNew: true,
      },
      {
        id: "marketing-strategy-advisor",
        title: "Marketing Strategy Advisor",
        subtitle: "For All",
        description: "Get advice on marketing strategies.",
        logo: "https://default-logo.com/placeholder.png",
        screenshot: ["/images/marketing-strategy-advisor.png"],
        coins: "Free",
        href: "/marketing-strategy-advisor",
        tags: ["marketing", "strategy"],
        isNew: true,
      },
      {
        id: "product-description-generator",
        title: "Product Description Generator",
        subtitle: "For All",
        description: "Generate product descriptions for e-commerce.",
        logo: "https://default-logo.com/placeholder.png",
        screenshot: ["/images/product-description-generator.png"],
        coins: "Free",
        href: "/product-description-generator",
        tags: ["marketing", "writing"],
        isNew: true,
      },
      {
        id: "competitor-insight-ai",
        title: "Competitor Insight AI",
        subtitle: "For All",
        description: "Get insights about competitors.",
        logo: "https://default-logo.com/placeholder.png",
        screenshot: ["/images/competitor-insight-ai.png"],
        coins: "Free",
        href: "/competitor-insight-ai",
        tags: ["marketing", "analytics"],
        isNew: true,
      },
      {
        id: "seo-master-ai",
        title: "SEO Master AI",
        subtitle: "For All",
        description: "Optimize your content for search engines.",
        logo: "https://default-logo.com/placeholder.png",
        screenshot: ["/images/seo-master-ai.png"],
        coins: "Free",
        href: "/seo-master-ai",
        tags: ["marketing", "seo"],
        isNew: true,
      },
      {
        id: "ad-script-generator",
        title: "Ad Script Generator",
        subtitle: "For All",
        description: "Generate scripts for advertisements.",
        logo: "https://default-logo.com/placeholder.png",
        screenshot: ["/images/ad-script-generator.png"],
        coins: "Free",
        href: "/ad-script-generator",
        tags: ["marketing", "writing"],
        isNew: true,
      },
      {
        id: "ad-targeting-ai",
        title: "Ad Targeting AI",
        subtitle: "For All",
        description: "Get insights on ad targeting.",
        logo: "https://default-logo.com/placeholder.png",
        screenshot: ["/images/ad-targeting-ai.png"],
        coins: "Free",
        href: "/ad-targeting-ai",
        tags: ["marketing", "advertising"],
        isNew: true,
      },
      {
        id: "product-innovator-ai",
        title: "Product Innovator AI",
        subtitle: "For All",
        description: "Get innovative product ideas.",
        logo: "https://default-logo.com/placeholder.png",
        screenshot: ["/images/product-innovator-ai.png"],
        coins: "Free",
        href: "/product-innovator-ai",
        tags: ["marketing", "innovation"],
        isNew: true,
      },
      {
        id: "entrepreneur-insights",
        title: "Entrepreneur Insights",
        subtitle: "For All",
        description: "Get insights for entrepreneurs.",
        logo: "https://default-logo.com/placeholder.png",
        screenshot: ["/images/entrepreneur-insights.png"],
        coins: "Free",
        href: "/entrepreneur-insights",
        tags: ["marketing", "business"],
        isNew: true,
      },
      {
        id: "casestudy-genius",
        title: "CaseStudy Genius",
        subtitle: "For All",
        description: "Generate case studies for marketing.",
        logo: "https://default-logo.com/placeholder.png",
        screenshot: ["/images/casestudy-genius.png"],
        coins: "Free",
        href: "/casestudy-genius",
        tags: ["marketing", "writing"],
        isNew: true,
      },
      {
        id: "text-simplifier",
        title: "TextSimplifier",
        subtitle: "For All",
        description: "Simplify complex text for better understanding.",
        logo: "https://default-logo.com/placeholder.png",
        screenshot: ["/images/text-simplifier.png"],
        coins: "Free",
        href: "/text-simplifier",
        tags: ["marketing", "writing"],
        isNew: true,
      },
      {
        id: "knowyourniche",
        title: "KnowYourNiche",
        subtitle: "For All",
        description: "Get insights about your niche.",
        logo: "https://default-logo.com/placeholder.png",
        screenshot: ["/images/knowyourniche.png"],
        coins: "Free",
        href: "/knowyourniche",
        tags: ["marketing", "research"],
        isNew: true,
      },
      {
        id: "instaoptimizer",
        title: "InstaOptimizer",
        subtitle: "For All",
        description: "Optimize your Instagram profile.",
        logo: "https://default-logo.com/placeholder.png",
        screenshot: ["/images/instaoptimizer.png"],
        coins: "Free",
        href: "/instaoptimizer",
        tags: ["marketing", "social"],
        isNew: true,
      },
      {
        id: "slogan-generator",
        title: "Slogan Generator",
        subtitle: "For All",
        description: "Generate catchy slogans.",
        logo: "https://default-logo.com/placeholder.png",
        screenshot: ["/images/slogan-generator.png"],
        coins: "Free",
        href: "/slogan-generator",
        tags: ["marketing", "branding"],
        isNew: true,
      },
      {
        id: "seo-meta-description-generator",
        title: "SEO Meta Description Generator",
        subtitle: "For All",
        description: "Generate SEO-friendly meta descriptions.",
        logo: "https://default-logo.com/placeholder.png",
        screenshot: ["/images/seo-meta-description-generator.png"],
        coins: "Free",
        href: "/seo-meta-description-generator",
        tags: ["marketing", "seo"],
        isNew: true,
      },
      {
        id: "ad-copy-generator",
        title: "Ad Copy Generator",
        subtitle: "For All",
        description: "Generate ad copy for various platforms.",
        logo: "https://default-logo.com/placeholder.png",
        screenshot: ["/images/ad-copy-generator.png"],
        coins: "Free",
        href: "/ad-copy-generator",
        tags: ["marketing", "writing"],
        isNew: true,
      },
      {
        id: "brand-name-generator",
        title: "Brand Name Generator",
        subtitle: "For All",
        description: "Generate unique brand names.",
        logo: "https://default-logo.com/placeholder.png",
        screenshot: ["/images/brand-name-generator.png"],
        coins: "Free",
        href: "/brand-name-generator",
        tags: ["marketing", "branding"],
        isNew: true,
      },
      {
        id: "event-name-generator",
        title: "Event Name Generator",
        subtitle: "For All",
        description: "Generate names for events.",
        logo: "https://default-logo.com/placeholder.png",
        screenshot: ["/images/event-name-generator.png"],
        coins: "Free",
        href: "/event-name-generator",
        tags: ["marketing", "events"],
        isNew: true,
      },
      {
        id: "tagline-generator",
        title: "Tagline Generator",
        subtitle: "For All",
        description: "Generate taglines for brands.",
        logo: "https://default-logo.com/placeholder.png",
        screenshot: ["/images/tagline-generator.png"],
        coins: "Free",
        href: "/tagline-generator",
        tags: ["marketing", "branding"],
        isNew: true,
      },
      {
        id: "cold-email-generator",
        title: "Cold Email Generator",
        subtitle: "For All",
        description: "Generate cold emails for outreach.",
        logo: "https://default-logo.com/placeholder.png",
        screenshot: ["/images/cold-email-generator.png"],
        coins: "Free",
        href: "/cold-email-generator",
        tags: ["marketing", "writing"],
        isNew: true,
      },
      {
        id: "newsletter-title-generator",
        title: "Newsletter Title Generator",
        subtitle: "For All",
        description: "Generate titles for newsletters.",
        logo: "https://default-logo.com/placeholder.png",
        screenshot: ["/images/newsletter-title-generator.png"],
        coins: "Free",
        href: "/newsletter-title-generator",
        tags: ["marketing", "writing"],
        isNew: true,
      },
      {
        id: "brand-tagline-generator",
        title: "Brand Tagline Generator",
        subtitle: "For All",
        description: "Generate taglines for brands.",
        logo: "https://default-logo.com/placeholder.png",
        screenshot: ["/images/brand-tagline-generator.png"],
        coins: "Free",
        href: "/brand-tagline-generator",
        tags: ["marketing", "branding"],
        isNew: true,
      },
      {
        id: "article-title-generator",
        title: "Article Title Generator",
        subtitle: "For All",
        description: "Generate titles for articles.",
        logo: "https://default-logo.com/placeholder.png",
        screenshot: ["/images/article-title-generator.png"],
        coins: "Free",
        href: "/article-title-generator",
        tags: ["marketing", "writing"],
        isNew: true,
      },
      {
        id: "presentation-title-generator",
        title: "Presentation Title Generator",
        subtitle: "For All",
        description: "Generate titles for presentations.",
        logo: "https://default-logo.com/placeholder.png",
        screenshot: ["/images/presentation-title-generator.png"],
        coins: "Free",
        href: "/presentation-title-generator",
        tags: ["marketing", "writing"],
        isNew: true,
      },
      {
        id: "facebook-ad-copy-generator",
        title: "Facebook Ad Copy Generator",
        subtitle: "For All",
        description: "Generate ad copy for Facebook.",
        logo: "https://default-logo.com/placeholder.png",
        screenshot: ["/images/facebook-ad-copy-generator.png"],
        coins: "Free",
        href: "/facebook-ad-copy-generator",
        tags: ["marketing", "social"],
        isNew: true,
      },
      {
        id: "instagram-story-caption-generator",
        title: "Instagram Story Caption Generator",
        subtitle: "For All",
        description: "Generate captions for Instagram stories.",
        logo: "https://default-logo.com/placeholder.png",
        screenshot: ["/images/instagram-story-caption-generator.png"],
        coins: "Free",
        href: "/instagram-story-caption-generator",
        tags: ["marketing", "social"],
        isNew: true,
      },
      {
        id: "youtube-community-post-generator",
        title: "YouTube Community Post Generator",
        subtitle: "For All",
        description: "Generate community posts for YouTube.",
        logo: "https://default-logo.com/placeholder.png",
        screenshot: ["/images/youtube-community-post-generator.png"],
        coins: "Free",
        href: "/youtube-community-post-generator",
        tags: ["marketing", "social"],
        isNew: true,
      },
      {
        id: "tiktok-video-idea-generator",
        title: "TikTok Video Idea Generator",
        subtitle: "For All",
        description: "Generate ideas for TikTok videos.",
        logo: "https://default-logo.com/placeholder.png",
        screenshot: ["/images/tiktok-video-idea-generator.png"],
        coins: "Free",
        href: "/tiktok-video-idea-generator",
        tags: ["marketing", "social"],
        isNew: true,
      },
      {
        id: "tiktok-script-generator",
        title: "TikTok Script Generator",
        subtitle: "For All",
        description: "Generate scripts for TikTok videos.",
        logo: "https://default-logo.com/placeholder.png",
        screenshot: ["/images/tiktok-script-generator.png"],
        coins: "Free",
        href: "/tiktok-script-generator",
        tags: ["marketing", "social"],
        isNew: true,
      },
      {
        id: "event-tagline-generator",
        title: "Event Tagline Generator",
        subtitle: "For All",
        description: "Generate taglines for events.",
        logo: "https://default-logo.com/placeholder.png",
        screenshot: ["/images/event-tagline-generator.png"],
        coins: "Free",
        href: "/event-tagline-generator",
        tags: ["marketing", "events"],
        isNew: true,
      },
      {
        id: "startup-name-generator",
        title: "Startup Name Generator",
        subtitle: "For All",
        description: "Generate names for startups.",
        logo: "https://default-logo.com/placeholder.png",
        screenshot: ["/images/startup-name-generator.png"],
        coins: "Free",
        href: "/startup-name-generator",
        tags: ["marketing", "branding"],
        isNew: true,
      },
      {
        id: "conference-theme-generator",
        title: "Conference Theme Generator",
        subtitle: "For All",
        description: "Generate themes for conferences.",
        logo: "https://default-logo.com/placeholder.png",
        screenshot: ["/images/conference-theme-generator.png"],
        coins: "Free",
        href: "/conference-theme-generator",
        tags: ["marketing", "events"],
        isNew: true,
      },
      {
        id: "video-title-generator",
        title: "Video Title Generator",
        subtitle: "For All",
        description: "Generate titles for videos.",
        logo: "https://default-logo.com/placeholder.png",
        screenshot: ["/images/video-title-generator.png"],
        coins: "Free",
        href: "/video-title-generator",
        tags: ["marketing", "writing"],
        isNew: true,
      },
      {
        id: "email-subject-line-generator",
        title: "Email Subject Line Generator",
        subtitle: "For All",
        description: "Generate subject lines for emails.",
        logo: "https://default-logo.com/placeholder.png",
        screenshot: ["/images/email-subject-line-generator.png"],
        coins: "Free",
        href: "/email-subject-line-generator",
        tags: ["marketing", "writing"],
        isNew: true,
      },
      {
        id: "email-generator",
        title: "Email Generator",
        subtitle: "For All",
        description: "Generate emails for various purposes.",
        logo: "https://default-logo.com/placeholder.png",
        screenshot: ["/images/email-generator.png"],
        coins: "Free",
        href: "/email-generator",
        tags: ["marketing", "writing"],
        isNew: true,
      },
      {
        id: "ad-copy-generator",
        title: "Ad Copy Generator",
        subtitle: "For All",
        description: "Generate ad copy for various platforms.",
        logo: "https://default-logo.com/placeholder.png",
        screenshot: ["/images/ad-copy-generator.png"],
        coins: "Free",
        href: "/ad-copy-generator",
        tags: ["marketing", "writing"],
        isNew: true,
      },
    ],
  },
  {
    id: "healthcare",
    title: "HealthCare Tools",
    description: "Medical and wellness resources for healthcare professionals and individuals.",
    tools: [
      {
        id: "healthcare-tool-box",
        title: "HealthCare Tool Box",
        subtitle: "For All",
        description: "A collection of healthcare tools for professionals and individuals.",
        logo: "https://default-logo.com/placeholder.png",
        screenshot: ["/images/healthcare-toolbox.png"],
        coins: "Free",
        href: "/healthcare-tool-box",
        tags: ["healthcare", "utility"],
        isNew: true,
      },
      {
        id: "aarogya-healthcare-advisor",
        title: "Aarogya - HealthCare Advisor",
        subtitle: "For All",
        description: "Your personal health advisor.",
        logo: "https://default-logo.com/placeholder.png",
        screenshot: ["/images/aarogya-healthcare-advisor.png"],
        coins: "Free",
        href: "/aarogya-healthcare-advisor",
        tags: ["healthcare", "advisor"],
        isNew: true,
      },
      {
        id: "diet-planner",
        title: "Diet Planner",
        subtitle: "For All",
        description: "Plan your meals and track your diet.",
        logo: "https://default-logo.com/placeholder.png",
        screenshot: ["/images/diet-planner.png"],
        coins: "Free",
        href: "/diet-planner",
        tags: ["healthcare", "nutrition"],
        isNew: true,
      },
      {
        id: "kavya-psychiatrist-advisor",
        title: "Kavya - Psychiatrist Advisor",
        subtitle: "For All",
        description: "Mental health support and advice.",
        logo: "https://default-logo.com/placeholder.png",
        screenshot: ["/images/kavya-psychiatrist-advisor.png"],
        coins: "Free",
        href: "/kavya-psychiatrist-advisor",
        tags: ["healthcare", "mental-health"],
        isNew: true,
      },
    ],
  },
  {
    id: "social",
    title: "Social Media Tools",
    description: "Content creation and management tools for social media platforms and influencers.",
    tools: [
      {
        id: "instaoptimizer",
        title: "InstaOptimizer",
        subtitle: "For All",
        description: "Optimize your Instagram posts for maximum engagement.",
        logo: "https://default-logo.com/placeholder.png",
        screenshot: ["/images/instaoptimizer.png"],
        coins: "Free",
        href: "/instaoptimizer",
        tags: ["social", "marketing"],
        isNew: true,
      },
      {
        id: "caption-generator",
        title: "Caption Generator",
        subtitle: "For All",
        description: "Generate catchy captions for your social media posts.",
        logo: "https://default-logo.com/placeholder.png",
        screenshot: ["/images/caption-generator.png"],
        coins: "Free",
        href: "/caption-generator",
        tags: ["social", "writing"],
        isNew: true,
      },
      {
        id: "community-description-generator",
        title: "Community Description Generator",
        subtitle: "For All",
        description: "Create engaging descriptions for your online communities.",
        logo: "https://default-logo.com/placeholder.png",
        screenshot: ["/images/community-description-generator.png"],
        coins: "Free",
        href: "/community-description-generator",
        tags: ["social", "writing"],
        isNew: true,
      },
      {
        id: "linkedin-post-idea-generator",
        title: "LinkedIn Post Idea Generator",
        subtitle: "For All",
        description: "Generate professional post ideas for LinkedIn.",
        logo: "https://default-logo.com/placeholder.png",
        screenshot: ["/images/linkedin-post-idea-generator.png"],
        coins: "Free",
        href: "/linkedin-post-idea-generator",
        tags: ["social", "writing"],
        isNew: true,
      },
      {
        id: "pinterest-pin-idea-generator",
        title: "Pinterest Pin Idea Generator",
        subtitle: "For All",
        description: "Create eye-catching pin ideas for Pinterest.",
        logo: "https://default-logo.com/placeholder.png",
        screenshot: ["/images/pinterest-pin-idea-generator.png"],
        coins: "Free",
        href: "/pinterest-pin-idea-generator",
        tags: ["social", "designer"],
        isNew: true,
      },
      {
        id: "meme-caption-generator",
        title: "Meme Caption Generator",
        subtitle: "For All",
        description: "Generate funny captions for your memes.",
        logo: "https://default-logo.com/placeholder.png",
        screenshot: ["/images/meme-caption-generator.png"],
        coins: "Free",
        href: "/meme-caption-generator",
        tags: ["social", "writing"],
        isNew: true,
      },
      {
        id: "instagram-story-idea-generator",
        title: "Instagram Story Idea Generator",
        subtitle: "For All",
        description: "Get creative ideas for your Instagram stories.",
        logo: "https://default-logo.com/placeholder.png",
        screenshot: ["/images/instagram-story-idea-generator.png"],
        coins: "Free",
        href: "/instagram-story-idea-generator",
        tags: ["social", "marketing"],
        isNew: true,
      },
      {
        id: "youtube-description-generator",
        title: "YouTube Description Generator",
        subtitle: "For All",
        description: "Create compelling descriptions for your YouTube videos.",
        logo: "https://default-logo.com/placeholder.png",
        screenshot: ["/images/youtube-description-generator.png"],
        coins: "Free",
        href: "/youtube-description-generator",
        tags: ["social", "writing"],
        isNew: true,
      },
      {
        id: "youtube-seo-title-generator",
        title: "YouTube SEO Title Generator",
        subtitle: "For All",
        description: "Generate SEO-friendly titles for your YouTube videos.",
        logo: "https://default-logo.com/placeholder.png",
        screenshot: ["/images/youtube-seo-title-generator.png"],
        coins: "Free",
        href: "/youtube-seo-title-generator",
        tags: ["social", "marketing"],
        isNew: true,
      },
      {
        id: "add-emoji-to-text-generator",
        title: "Add Emoji to Text Generator",
        subtitle: "For All",
        description: "Enhance your text with relevant emojis.",
        logo: "https://default-logo.com/placeholder.png",
        screenshot: ["/images/add-emoji-to-text-generator.png"],
        coins: "Free",
        href: "/add-emoji-to-text-generator",
        tags: ["social", "writing"],
        isNew: true,
      },
      {
        id: "facebook-post-idea-generator",
        title: "Facebook Post Idea Generator",
        subtitle: "For All",
        description: "Generate engaging post ideas for Facebook.",
        logo: "https://default-logo.com/placeholder.png",
        screenshot: ["/images/facebook-post-idea-generator.png"],
        coins: "Free",
        href: "/facebook-post-idea-generator",
        tags: ["social", "marketing"],
        isNew: true,
      },
      {
        id: "twitter-tweet-generator",
        title: "Twitter Tweet Generator",
        subtitle: "For All",
        description: "Create catchy tweets for Twitter.",
        logo: "https://default-logo.com/placeholder.png",
        screenshot: ["/images/twitter-tweet-generator.png"],
        coins: "Free",
        href: "/twitter-tweet-generator",
        tags: ["social", "writing"],
        isNew: true,
      },
      {
        id: "reddit-post-idea-generator",
        title: "Reddit Post Idea Generator",
        subtitle: "For All",
        description: "Generate interesting post ideas for Reddit.",
        logo: "https://default-logo.com/placeholder.png",
        screenshot: ["/images/reddit-post-idea-generator.png"],
        coins: "Free",
        href: "/reddit-post-idea-generator",
        tags: ["social", "writing"],
        isNew: true,
      },
      {
        id: "podcast-episode-title-generator",
        title: "Podcast Episode Title Generator",
        subtitle: "For All",
        description: "Generate catchy titles for your podcast episodes.",
        logo: "https://default-logo.com/placeholder.png",
        screenshot: ["/images/podcast-episode-title-generator.png"],
        coins: "Free",
        href: "/podcast-episode-title-generator",
        tags: ["social", "marketing"],
        isNew: true,
      },
      {
        id: "character-name-generator",
        title: "Character Name Generator",
        subtitle: "For All",
        description: "Generate unique names for characters in your stories.",
        logo: "https://default-logo.com/placeholder.png",
        screenshot: ["/images/character-name-generator.png"],
        coins: "Free",
        href: "/character-name-generator",
        tags: ["social", "writing"],
        isNew: true,
      },
      {
        id: "social-media-bio-generator",
        title: "Social Media Bio Generator",
        subtitle: "For All",
        description: "Create engaging bios for your social media profiles.",
        logo: "https://default-logo.com/placeholder.png",
        screenshot: ["/images/social-media-bio-generator.png"],
        coins: "Free",
        href: "/social-media-bio-generator",
        tags: ["social", "writing"],
        isNew: true,
      },
      {
        id: "film-script-generator",
        title: "Film Script Generator",
        subtitle: "For All",
        description: "Generate scripts for films and videos.",
        logo: "https://default-logo.com/placeholder.png",
        screenshot: ["/images/film-script-generator.png"],
        coins: "Free",
        href: "/film-script-generator",
        tags: ["social", "writing"],
        isNew: true,
      },
      {
        id: "shorts-reels-companion",
        title: "Shorts & Reels Companion",
        subtitle: "For All",
        description: "Get ideas and scripts for shorts and reels.",
        logo: "https://default-logo.com/placeholder.png",
        screenshot: ["/images/shorts-reels-companion.png"],
        coins: "Free",
        href: "/shorts-reels-companion",
        tags: ["social", "marketing"],
        isNew: true,
      },
      {
        id: "pinterest-pin-description-generator",
        title: "Pinterest Pin Description Generator",
        subtitle: "For All",
        description: "Create engaging descriptions for your Pinterest pins.",
        logo: "https://default-logo.com/placeholder.png",
        screenshot: ["/images/pinterest-pin-description-generator.png"],
        coins: "Free",
        href: "/pinterest-pin-description-generator",
        tags: ["social", "writing"],
        isNew: true,
      },
      {
        id: "tiktok-caption-generator",
        title: "TikTok Caption Generator",
        subtitle: "For All",
        description: "Generate catchy captions for your TikTok videos.",
        logo: "https://default-logo.com/placeholder.png",
        screenshot: ["/images/tiktok-caption-generator.png"],
        coins: "Free",
        href: "/tiktok-caption-generator",
        tags: ["social", "writing"],
        isNew: true,
      },
      {
        id: "twitter-thread-generator",
        title: "Twitter Thread Generator",
        subtitle: "For All",
        description: "Create engaging Twitter threads.",
        logo: "https://default-logo.com/placeholder.png",
        screenshot: ["/images/twitter-thread-generator.png"],
        coins: "Free",
        href: "/twitter-thread-generator",
        tags: ["social", "writing"],
        isNew: true,
      },
      {
        id: "facebook-ad-copy-generator",
        title: "Facebook Ad Copy Generator",
        subtitle: "For All",
        description: "Generate ad copy for Facebook ads.",
        logo: "https://default-logo.com/placeholder.png",
        screenshot: ["/images/facebook-ad-copy-generator.png"],
        coins: "Free",
        href: "/facebook-ad-copy-generator",
        tags: ["social", "marketing"],
        isNew: true,
      },
      {
        id: "instagram-story-caption-generator",
        title: "Instagram Story Caption Generator",
        subtitle: "For All",
        description: "Generate captions for your Instagram stories.",
        logo: "https://default-logo.com/placeholder.png",
        screenshot: ["/images/instagram-story-caption-generator.png"],
        coins: "Free",
        href: "/instagram-story-caption-generator",
        tags: ["social", "marketing"],
        isNew: true,
      },
      {
        id: "youtube-community-post-generator",
        title: "YouTube Community Post Generator",
        subtitle: "For All",
        description: "Generate community posts for YouTube.",
        logo: "https://default-logo.com/placeholder.png",
        screenshot: ["/images/youtube-community-post-generator.png"],
        coins: "Free",
        href: "/youtube-community-post-generator",
        tags: ["social", "marketing"],
        isNew: true,
      },
      {
        id: "tiktok-video-idea-generator",
        title: "TikTok Video Idea Generator",
        subtitle: "For All",
        description: "Generate ideas for TikTok videos.",
        logo: "https://default-logo.com/placeholder.png",
        screenshot: ["/images/tiktok-video-idea-generator.png"],
        coins: "Free",
        href: "/tiktok-video-idea-generator",
        tags: ["social", "marketing"],
        isNew: true,
      },
      {
        id: "tiktok-script-generator",
        title: "TikTok Script Generator",
        subtitle: "For All",
        description: "Generate scripts for TikTok videos.",
        logo: "https://default-logo.com/placeholder.png",
        screenshot: ["/images/tiktok-script-generator.png"],
        coins: "Free",
        href: "/tiktok-script-generator",
        tags: ["social", "writing"],
        isNew: true,
      },
      {
        id: "instagram-bio-generator",
        title: "Instagram Bio Generator",
        subtitle: "For All",
        description: "Create engaging bios for your Instagram profile.",
        logo: "https://default-logo.com/placeholder.png",
        screenshot: ["/images/instagram-bio-generator.png"],
        coins: "Free",
        href: "/instagram-bio-generator",
        tags: ["social", "writing"],
        isNew: true,
      },
      {
        id: "facebook-group-post-idea-generator",
        title: "Facebook Group Post Idea Generator",
        subtitle: "For All",
        description: "Generate ideas for Facebook group posts.",
        logo: "https://default-logo.com/placeholder.png",
        screenshot: ["/images/facebook-group-post-idea-generator.png"],
        coins: "Free",
        href: "/facebook-group-post-idea-generator",
        tags: ["social", "marketing"],
        isNew: true,
      },
      {
        id: "linkedin-article-idea-generator",
        title: "LinkedIn Article Idea Generator",
        subtitle: "For All",
        description: "Generate ideas for LinkedIn articles.",
        logo: "https://default-logo.com/placeholder.png",
        screenshot: ["/images/linkedin-article-idea-generator.png"],
        coins: "Free",
        href: "/linkedin-article-idea-generator",
        tags: ["social", "writing"],
        isNew: true,
      },
      {
        id: "pinterest-board-name-generator",
        title: "Pinterest Board Name Generator",
        subtitle: "For All",
        description: "Generate names for Pinterest boards.",
        logo: "https://default-logo.com/placeholder.png",
        screenshot: ["/images/pinterest-board-name-generator.png"],
        coins: "Free",
        href: "/pinterest-board-name-generator",
        tags: ["social", "writing"],
        isNew: true,
      },
      {
        id: "instagram-highlight-name-generator",
        title: "Instagram Highlight Name Generator",
        subtitle: "For All",
        description: "Generate names for Instagram highlights.",
        logo: "https://default-logo.com/placeholder.png",
        screenshot: ["/images/instagram-highlight-name-generator.png"],
        coins: "Free",
        href: "/instagram-highlight-name-generator",
        tags: ["social", "writing"],
        isNew: true,
      },
      {
        id: "youtube-channel-description-generator",
        title: "YouTube Channel Description Generator",
        subtitle: "For All",
        description: "Generate descriptions for your YouTube channel.",
        logo: "https://default-logo.com/placeholder.png",
        screenshot: ["/images/youtube-channel-description-generator.png"],
        coins: "Free",
        href: "/youtube-channel-description-generator",
        tags: ["social", "writing"],
        isNew: true,
      },
      {
        id: "linkedin-headline-generator",
        title: "LinkedIn Headline Generator",
        subtitle: "For All",
        description: "Create engaging headlines for your LinkedIn profile.",
        logo: "https://default-logo.com/placeholder.png",
        screenshot: ["/images/linkedin-headline-generator.png"],
        coins: "Free",
        href: "/linkedin-headline-generator",
        tags: ["social", "writing"],
        isNew: true,
      },
      {
        id: "twitter-bio-generator",
        title: "Twitter Bio Generator",
        subtitle: "For All",
        description: "Create engaging bios for your Twitter profile.",
        logo: "https://default-logo.com/placeholder.png",
        screenshot: ["/images/twitter-bio-generator.png"],
        coins: "Free",
        href: "/twitter-bio-generator",
        tags: ["social", "writing"],
        isNew: true,
      },
      {
        id: "pinterest-pin-title-generator",
        title: "Pinterest Pin Title Generator",
        subtitle: "For All",
        description: "Generate titles for your Pinterest pins.",
        logo: "https://default-logo.com/placeholder.png",
        screenshot: ["/images/pinterest-pin-title-generator.png"],
        coins: "Free",
        href: "/pinterest-pin-title-generator",
        tags: ["social", "writing"],
        isNew: true,
      },
      {
        id: "instagram-hashtag-generator",
        title: "Instagram Hashtag Generator",
        subtitle: "For All",
        description: "Generate hashtags for your Instagram posts.",
        logo: "https://default-logo.com/placeholder.png",
        screenshot: ["/images/instagram-hashtag-generator.png"],
        coins: "Free",
        href: "/instagram-hashtag-generator",
        tags: ["social", "marketing"],
        isNew: true,
      },
      {
        id: "youtube-playlist-name-generator",
        title: "YouTube Playlist Name Generator",
        subtitle: "For All",
        description: "Generate names for your YouTube playlists.",
        logo: "https://default-logo.com/placeholder.png",
        screenshot: ["/images/youtube-playlist-name-generator.png"],
        coins: "Free",
        href: "/youtube-playlist-name-generator",
        tags: ["social", "writing"],
        isNew: true,
      },
      {
        id: "recipe-name-generator",
        title: "Recipe Name Generator",
        subtitle: "For All",
        description: "Generate names for your recipes.",
        logo: "https://default-logo.com/placeholder.png",
        screenshot: ["/images/recipe-name-generator.png"],
        coins: "Free",
        href: "/recipe-name-generator",
        tags: ["social", "writing"],
        isNew: true,
      },
      {
        id: "webinar-title-generator",
        title: "Webinar Title Generator",
        subtitle: "For All",
        description: "Generate titles for your webinars.",
        logo: "https://default-logo.com/placeholder.png",
        screenshot: ["/images/webinar-title-generator.png"],
        coins: "Free",
        href: "/webinar-title-generator",
        tags: ["social", "marketing"],
        isNew: true,
      },
      {
        id: "video-title-generator",
        title: "Video Title Generator",
        subtitle: "For All",
        description: "Generate titles for your videos.",
        logo: "https://default-logo.com/placeholder.png",
        screenshot: ["/images/video-title-generator.png"],
        coins: "Free",
        href: "/video-title-generator",
        tags: ["social", "marketing"],
        isNew: true,
      },
    ],
  },
  {
    id: "legal",
    title: "Legal Tools",
    description: "Document preparation and legal research assistants for legal professionals.",
    tools: [
      {
        id: "legal-tool-box",
        title: "Legal Tool Box",
        subtitle: "For Legal Professionals",
        description: "A comprehensive toolkit for legal professionals.",
        logo: "https://default-logo.com/placeholder.png",
        screenshot: ["/images/legal-tool-box.png"],
        coins: "Free",
        href: "/legal-tool-box",
        tags: ["legal", "utility"],
        isNew: true,
      },
      {
        id: "vidharini-legal-advisor",
        title: "Vidharini - Legal Advisor",
        subtitle: "For Legal Professionals",
        description: "AI-powered legal advice at your fingertips.",
        logo: "https://default-logo.com/placeholder.png",
        screenshot: ["/images/vidharini-legal-advisor.png"],
        coins: "Free",
        href: "/vidharini-legal-advisor",
        tags: ["legal", "advisor"],
        isNew: true,
      },
    ],
  },
  {
    id: "fintech",
    title: "Fintech Tools",
    description: "Financial technology solutions for personal and business finance management.",
    tools: [
      {
        id: "fintech-tool-box",
        title: "Fintech Tool Box",
        subtitle: "For Financial Professionals",
        description: "A suite of tools for financial management.",
        logo: "https://default-logo.com/placeholder.png",
        screenshot: ["/images/fintech-tool-box.png"],
        coins: "Free",
        href: "/fintech-tool-box",
        tags: ["fintech", "finance"],
        isNew: true,
      },
    ],
  },
];


export const PREFERENCE_OPTIONS: PreferenceOption[] = [
  {
    id: "productivity",
    title: "Productivity & Organization",
    description: "Tools to boost your efficiency and organize your work",
    tags: ["productivity", "utility", "organization"],
    icon: "⚡"
  },
  {
    id: "design_creative",
    title: "Design & Creative",
    description: "Create stunning visuals, logos, and multimedia content",
    tags: ["designer", "creativity", "branding", "audio", "music"],
    icon: "🎨"
  },
  {
    id: "marketing_business",
    title: "Marketing & Business",
    description: "Grow your business and enhance your marketing efforts",
    tags: ["marketing", "business", "social", "branding"],
    icon: "📈"
  },
  {
    id: "writing_content",
    title: "Writing & Content",
    description: "Create, edit, and translate written content",
    tags: ["writing", "content", "translation"],
    icon: "✍️"
  },
  {
    id: "health_wellness",
    title: "Health & Wellness",
    description: "Mental health support and wellness tools",
    tags: ["healthcare", "support", "wellness"],
    icon: "🏥"
  },
  {
    id: "education_career",
    title: "Education & Career",
    description: "Learn new skills and advance your career",
    tags: ["education", "career", "learning"],
    icon: "🎓"
  },
  {
    id: "finance_fintech",
    title: "Finance & FinTech",
    description: "Manage finances and explore financial technologies",
    tags: ["finance", "fintech", "investment", "budgeting"],
    icon: "💰"
  },
  {
    id: "development_tech",
    title: "Development & Tech",
    description: "Programming tools and technical resources",
    tags: ["development", "programming", "tech", "coding"],
    icon: "💻"
  },
  {
    id: "data_analytics",
    title: "Data & Analytics",
    description: "Analyze data and generate insights",
    tags: ["analytics", "data", "insights", "reporting"],
    icon: "📊"
  },
  {
    id: "communication",
    title: "Communication & Collaboration",
    description: "Connect and collaborate with others effectively",
    tags: ["communication", "collaboration", "teamwork"],
    icon: "💬"
  }
];